### ISSUE TITLE
Contradiction

### ISSUE THREAD

**Issue by Aidanamite** [DTMosken/Buyable-Blueprints#1]
The point of the Misc Cheats mod was so that there was 1 mod instead of each of the indivdual features being their own mod and making a mess of the website.

Splitting the features into individual mods goes against the whole point of the mod you're copying from.

**Comment by DTMosken** [comment]
thank you for your comment, in my view some users (like me) may prefer a separate mode for some features but not the others for the convinience of managing servers. But I understand and appreciate your concerns.

**Comment by Aidanamite** [comment]
you can turn on and off every feature.... if you want to play with only one of the features you can do that without seperating it into it's own mod
